[tool.poetry]
name = "100daysofcodepython-1"
version = "0.1.0"
description = ""
authors = ["nuthanm <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
bs4 = "^0.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
